### ISSUE TITLE
Exception thrown for classes where package name directory contains '.'

### ISSUE THREAD

**Issue by foxdk** [basepom/duplicate-finder-maven-plugin#29]
An exception (like the one shown below) is thrown if duplicates are found in a jar file's class which contains a dot in one of the directories composing the package name. For example, if my jar file is jaxb-osgi-2.2.5-2.jar
and my duplicated class is 1.0.org.apache.xml.resolver.tools.ResolvingXMLFilter
then I will get the exception shown below, because the resource name in the jar file is actually
     1.0/org/apache/xml/resolver/tools/ResolvingXMLFilter.class
instead of
     1/0/org/apache/xml/resolver/tools/ResolvingXMLFilter.class
like the code is written to look for (having earlier done a global search and replace of '.' with '/').

[WARNING] Could not read content from file /Users/foxdk/.m2/repository/com/sun/xml/bind/jaxb-osgi/2.2.5-2/jaxb-osgi-2.2.5-2.jar!
java.io.IOException: Could not find 1/0/org/apache/xml/resolver/tools/ResolvingXMLFilter.class in archive /Users/foxdk/.m2/repository/com/sun/xml/bind/jaxb-osgi/2.2.5-2/jaxb-osgi-2.2.5-2.jar
	at org.basepom.mojo.duplicatefinder.DuplicateFinderMojo.getSHA256HexOfElement(DuplicateFinderMojo.java:606)
	at org.basepom.mojo.duplicatefinder.DuplicateFinderMojo.determineConflictState(DuplicateFinderMojo.java:554)
	at org.basepom.mojo.duplicatefinder.DuplicateFinderMojo.checkForDuplicates(DuplicateFinderMojo.java:536)
	at org.basepom.mojo.duplicatefinder.DuplicateFinderMojo.checkClasspath(DuplicateFinderMojo.java:490)
	at org.basepom.mojo.duplicatefinder.DuplicateFinderMojo.execute(DuplicateFinderMojo.java:379)

**Comment by hgschmie** [comment]
Ok, I see what you are saying. This is a weird jar.

**Comment by hgschmie** [comment]
I am pretty sure that you can not exclude the files using class name patterns. "1.0" is not a legal package identifier and not a legal class name either. What should be possible is to exclude these as resource patterns. I will add an integration test for this.

What would be really helpful if you had a test case of what exactly you are trying to accomplish and whether this error happens all the time or only when you add a specific resource or class pattern.

**Comment by hgschmie** [comment]
This change requires quite a bit of reworking of the logic how pathes are translated to package names. I am still pretty sure that you can not get away with 1.0.<some package> for a class exclusion but you have to do a resource exclusion. 

I released 1.3.0 without my work in progress here because I will not be able to work on this for a while. I will try to get this into a 1.3.1 release.

**Comment by hgschmie** [comment]
the fix for #33 also reworks the way package names are parsed. As a result, the elements in the 1.0 subfolder are now considered resources, not classes. There is probably some way that the OSGi classloader shims those onto the class path proper; the plugin will not accommodate for that (unless someone sends in a patch). The jar no longer causes the plugin to crash.
