### ISSUE TITLE
Ignore /META-INF/versions/9/module-info.class by default

### ISSUE THREAD

**Issue by Mortinke** [basepom/duplicate-finder-maven-plugin#33]
We have the same issue with `/META-INF/versions/9/module-info.clas` files as in #31.
e.g. https://travis-ci.org/zalando/logbook/jobs/448681344 or [#31 comment](https://github.com/basepom/duplicate-finder-maven-plugin/issues/31#issuecomment-434622193)

**Comment by mpellegrini** [comment]
Wondering if the mentioned PR mentioned above would get merged?

**Comment by hgschmie** [comment]
Hi, thanks for the ping. This is related to multi-release jars and requires a more comprehensive change to the plugin. I am planning to do this when I find time. 

As a workaround, you can add this pattern in your pom as well.

**Comment by mpellegrini** [comment]
Thanks for the quick reply.  I have added the ignore pattern to my pom for the time being.

Thanks for your work on producing a very useful plugin!!

**Comment by stevenschlansker** [comment]
This problem is continuing to spread -- latest releases of very popular jars like `assertj` and `byte-buddy` now conflict with each other.

**Comment by hgschmie** [comment]
I need to find time to work out how to deal with multi-release jars. PRs very welcome

**Comment by hgschmie** [comment]
This is fixed in the next version. I am planning that the next version will be the last one that runs on JDK8 and the one after will be JDK9+ exclusive.

In that version, I am planning to do more work with multi-release jars; currently there is a corner case where a duplicate class is not detected:

```
Base jar contains no conflicts
  |
  +-- META-INF/versions/9/A.class    is a conflict with an existing class on the class path
```

the current plugin would not detect this conflict when running under JDK9. To be able to manage these type of conflicts, the code must analyze the Multi-Release flag from the manifest and then build a map on which classes are actually visible on the class path. Very doable but I see no point in doing this for the JDK 8 version.
